{
    "name": "Website Snippet All",
    "category": "Website",
    "version": "12.0.1.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "website": "https://technolibre.ca",
    "application": True,
    "depends": ["website_animate"],
    "data": [
        "views/snippets.xml",
        "views/assets.xml",
        "views/image_content.xml",
        "views/snippets_options.xml",
        "views/s_color_blocks_2.xml",
        "views/s_color_blocks_4.xml",
        "views/s_column.xml",
        "views/s_two_columns.xml",
        "views/s_three_columns_circle.xml",
        "views/s_timeline.xml",
        "views/s_event_list.xml",
        "views/s_discount.xml",
        "views/s_pricing.xml",
        "views/s_process_steps.xml",
        "views/s_icon_box.xml",
        "views/s_big_image.xml",
        "views/s_big_image_parallax.xml",
        "views/s_text_highlight.xml",
        "views/s_progress_bar.xml",
        "views/s_team_profiles.xml",
        "views/s_profile.xml",
        "views/s_animated_boxes.xml",
        "views/s_showcase.xml",
        "views/s_numbers.xml",
        "views/s_media_list.xml",
        "views/s_masonry_block.xml",
        "views/s_media_block.xml",
        "views/s_showcase_slider.xml",
        "views/s_color_blocks_img.xml",
        "views/s_text_picture_text.xml",
        "views/s_header_text_big_picture.xml",
        "views/s_product_list.xml",
        "views/s_features_carousel.xml",
        "views/s_products_carousel.xml",
        "views/s_big_icons.xml",
        "views/s_banner_parallax.xml",
        "views/s_news_carousel.xml",
        "views/s_badge.xml",
        "views/s_showcase_image.xml",
    ],
    "installable": True,
}
