{
    "name": "Website Snippet All",
    "category": "Website",
    "version": "12.0.1.0",
    "author": "TechnoLibre",
    "license": "AGPL-3",
    "website": "https://technolibre.ca",
    "application": True,
    "depends": ["website"],
    "data": [
        "views/snippets.xml",
        "views/assets.xml",
        "views/s_color_blocks_2.xml",
        "views/s_color_blocks_4.xml",
        "views/s_column.xml",
        "views/s_two_columns.xml",
        "views/s_three_columns_circle.xml",
        "views/s_timeline.xml",
        "views/s_event_list.xml",
        "views/s_discount.xml",
        "views/s_pricing.xml",
        "views/s_process_steps.xml",
    ],
    "installable": True,
}
